-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.95,
        blur = {
            passes = 4,
            size = 5,
            special = true,
        },
        dim_special = 0.3,
        fullscreen_opacity = 1.0,
        inactive_opacity = 0.85,
        rounding = 10,
    },
    dwindle = {
        preserve_split = true,
    },
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
    general = {
        border_size = 2,
        extend_border_grab_area = 10,
        gaps_in = 3,
        gaps_out = 8,
        resize_on_border = true,
    },
    input = {
        accel_profile = "flat",
        kb_options = "ctrl:nocaps",
    },
    misc = {
        vrr = 3,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@239.76Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Workspaces
hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
})
hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
})
hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
})
hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
})
hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
})

-- Keybinds
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen())
hl.unbind("SUPER + ALT + Space")
hl.bind("SUPER + ALT + Space", hl.dsp.window.float({ action = "toggle" }))
hl.unbind("SUPER + backslash")
hl.bind("SUPER + backslash", hl.dsp.layout("togglesplit"))
hl.unbind("SUPER + Escape")
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("hyprctl kill"))
hl.unbind("ALT + Tab")
hl.bind("ALT + Tab", hl.dsp.window.cycle_next())
hl.unbind("SUPER + Tab")
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("noctalia msg window-switcher"))
hl.unbind("SUPER + H")
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))
hl.unbind("SUPER + J")
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))
hl.unbind("SUPER + SHIFT + Left")
hl.bind("SUPER + SHIFT + Left", hl.dsp.window.move({ direction = "left" }))
hl.unbind("SUPER + SHIFT + Right")
hl.bind("SUPER + SHIFT + Right", hl.dsp.window.move({ direction = "right" }))
hl.unbind("SUPER + SHIFT + Up")
hl.bind("SUPER + SHIFT + Up", hl.dsp.window.move({ direction = "up" }))
hl.unbind("SUPER + SHIFT + Down")
hl.bind("SUPER + SHIFT + Down", hl.dsp.window.move({ direction = "down" }))
hl.unbind("SUPER + 1")
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.unbind("SUPER + 2")
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.unbind("SUPER + 3")
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.unbind("SUPER + 4")
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.unbind("SUPER + 5")
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.unbind("SUPER + 6")
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.unbind("SUPER + SHIFT + 1")
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.unbind("SUPER + SHIFT + 2")
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.unbind("SUPER + SHIFT + 3")
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.unbind("SUPER + SHIFT + 4")
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.unbind("SUPER + SHIFT + 5")
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.unbind("SUPER + SHIFT + 6")
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.unbind("SUPER + CTRL + Left")
hl.bind("SUPER + CTRL + Left", hl.dsp.focus({ workspace = "m-1" }))
hl.unbind("SUPER + CTRL + Right")
hl.bind("SUPER + CTRL + Right", hl.dsp.focus({ workspace = "m+1" }))
hl.unbind("SUPER + CTRL + Down")
hl.bind("SUPER + CTRL + Down", hl.dsp.focus({ workspace = "emptym" }))
hl.unbind("SUPER + mouse_down")
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "m-1" }))
hl.unbind("SUPER + mouse_up")
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "m+1" }))
hl.unbind("SUPER + SHIFT + CTRL + Left")
hl.bind("SUPER + CTRL + SHIFT + Left", hl.dsp.window.move({ workspace = "m-1" }))
hl.unbind("SUPER + SHIFT + CTRL + Right")
hl.bind("SUPER + CTRL + SHIFT + Right", hl.dsp.window.move({ workspace = "m+1" }))
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("Magic"))
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("/home/isaac/.config/foot/new-window"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("uwsm app -- dolphin"))
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.workspace.toggle_special("Chrome"))
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("uwsm app -- gnome-calculator"))
hl.unbind("XF86Calculator")
hl.bind("XF86Calculator", hl.dsp.exec_cmd("uwsm app -- gnome-calculator"))
hl.unbind("SHIFT + CTRL + Escape")
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd("uwsm app -- ghostty -e btop"))
hl.unbind("SUPER + Space")
hl.bind("SUPER + Space", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"))
hl.unbind("SUPER + period")
hl.bind("SUPER + period", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher /emo"))
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("noctalia msg panel-toggle clipboard"))
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center notifications"))
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center"))
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("noctalia msg settings-toggle"))
hl.unbind("SUPER + ALT + C")
hl.bind("SUPER + ALT + C", hl.dsp.exec_cmd("noctalia msg panel-toggle session"))
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("noctalia msg panel-toggle wallpaper"))
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("noctalia msg screenshot-region"))
hl.unbind("SUPER + Print")
hl.bind("SUPER + Print", hl.dsp.exec_cmd("noctalia msg screenshot-fullscreen"))
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("hyprpicker -a -n"))
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.workspace.toggle_special("Steam"))
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:Magic" }))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.group.toggle())
hl.unbind("SUPER + ALT + P")
hl.bind("SUPER + ALT + P", hl.dsp.window.pin())
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.workspace.toggle_special("Chat"))
hl.unbind("SUPER + ALT + H")
hl.bind("SUPER + ALT + H", hl.dsp.group.prev())
hl.unbind("SUPER + ALT + L")
hl.bind("SUPER + ALT + L", hl.dsp.group.next())
hl.unbind("SUPER + SHIFT + Q")
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_raw("/home/isaac/.local/bin/wsclose"))
hl.unbind("SUPER + SHIFT + B")
hl.bind("SUPER + SHIFT + B", hl.dsp.window.move({ workspace = "special:Chrome" }))
hl.unbind("SUPER + mouse:272")
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), {
    mouse = true,
})
hl.unbind("SUPER + mouse:273")
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), {
    mouse = true,
})
hl.unbind("XF86AudioRaiseVolume")
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("noctalia msg volume-up"), {
    repeating = true,
    locked = true,
})
hl.unbind("XF86AudioLowerVolume")
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("noctalia msg volume-down"), {
    repeating = true,
    locked = true,
})
hl.unbind("XF86MonBrightnessUp")
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("noctalia msg brightness-up"), {
    repeating = true,
    locked = true,
})
hl.unbind("XF86MonBrightnessDown")
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("noctalia msg brightness-down"), {
    repeating = true,
    locked = true,
})
hl.unbind("XF86AudioMute")
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("noctalia msg volume-mute"), {
    locked = true,
})
hl.unbind("XF86AudioMicMute")
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("noctalia msg mic-mute"), {
    locked = true,
})
hl.unbind("XF86AudioPlay")
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("noctalia msg media toggle"), {
    locked = true,
})
hl.unbind("XF86AudioPause")
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("noctalia msg media toggle"), {
    locked = true,
})
hl.unbind("XF86AudioNext")
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("noctalia msg media next"), {
    locked = true,
})
hl.unbind("XF86AudioPrev")
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("noctalia msg media previous"), {
    locked = true,
})

-- Window rules
hl.window_rule({
    match = {
        float = true,
    },
    center = true,
})
hl.window_rule({
    match = {
        float = true,
    },
    persistent_size = true,
})
hl.window_rule({
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    keep_aspect_ratio = true,
})
hl.window_rule({
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    pin = true,
})
hl.window_rule({
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    size = "['max(monitor_w, monitor_h)*0.25', 'min(monitor_w, monitor_h)*0.25']",
})
hl.window_rule({
    match = {
        content = "game",
    },
    workspace = "name:gaming",
})
hl.window_rule({
    match = {
        xdg_tag = "^(.*game.*)$",
    },
    content = "game",
})
hl.window_rule({
    match = {
        xdg_tag = "^(.*game.*)$",
    },
    fullscreen_state = 2,
})
hl.window_rule({
    match = {
        xdg_tag = "^(.*game.*)$",
    },
    sync_fullscreen = true,
})
hl.window_rule({
    match = {
        xdg_tag = "^(.*game.*)$",
    },
    workspace = "name:gaming",
})
hl.window_rule({
    match = {
        class = "^(steam_app.*|gamescope)$",
    },
    workspace = "name:gaming",
})
hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(Friends List)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(Launching\\.{3})$",
    },
    center = true,
})
hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(Launching\\.{3})$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(Launching\\.{3})$",
    },
    workspace = "name:gaming",
})
hl.window_rule({
    match = {
        class = "^(steam_app.*|gamescope)$",
        initial_title = "negative:^(.*\\home\\.*)$",
        title = "^(.+)$",
    },
    content = "game",
})
hl.window_rule({
    match = {
        class = "^(steam_app.*|gamescope)$",
        initial_title = "negative:^(.*\\home\\.*)$",
        title = "^(.+)$",
    },
    decorate = false,
})
hl.window_rule({
    match = {
        class = "^(steam_app.*|gamescope)$",
        initial_title = "negative:^(.*\\home\\.*)$",
        title = "^(.+)$",
    },
    fullscreen_state = 2,
})
hl.window_rule({
    match = {
        class = "^(steam_app.*|gamescope)$",
        initial_title = "negative:^(.*\\home\\.*)$",
        title = "^(.+)$",
    },
    size = "['monitor_w', 'monitor_h']",
})
hl.window_rule({
    match = {
        class = "^(steam_app.*|gamescope)$",
        initial_title = "negative:^(.*\\home\\.*)$",
        title = "^(.+)$",
    },
    sync_fullscreen = true,
})
hl.window_rule({
    match = {
        class = "^(steam_app.*)$",
        initial_title = "^$",
    },
    center = true,
})
hl.window_rule({
    match = {
        class = "^(steam_app.*)$",
        initial_title = "^$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(steam_app.*)$",
        initial_title = "^$",
    },
    fullscreen = false,
})
hl.window_rule({
    match = {
        class = "^(steam_app.*)$",
        initial_title = "^$",
    },
    fullscreen_state = 0,
})
hl.window_rule({
    match = {
        class = "^(steam_app.*)$",
        initial_title = "^$",
    },
    workspace = "name:gaming",
})
hl.window_rule({
    match = {
        class = "^(.*\\.exe)$",
        float = true,
    },
    center = true,
})
hl.window_rule({
    match = {
        class = "^(.*\\.exe)$",
        float = true,
    },
    fullscreen_state = 0,
})
hl.window_rule({
    match = {
        class = "^(.*\\.exe)$",
        float = true,
    },
    monitor = "HDMI-A-1",
})
hl.window_rule({
    match = {
        class = "^(.*[Ll]auncher.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(.*[Ll]auncher.*)$",
    },
    monitor = "HDMI-A-1",
})
hl.window_rule({
    match = {
        class = "^(.*[Cc]alc.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(.*[Cc]alc.*)$",
    },
    size = "['max(monitor_w, monitor_h)*0.17', 'min(monitor_w, monitor_h)*0.43']",
})
hl.window_rule({
    match = {
        class = "^(org\\.kde\\.keditfiletype)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(org\\.kde\\.ark)$",
    },
    size = "['max(monitor_w, monitor_h)*0.40', 'min(monitor_w, monitor_h)*0.40']",
})
hl.window_rule({
    match = {
        class = "^(.*satty.*)$",
        title = "^(Satty)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(.*satty.*)$",
        title = "^(Satty)$",
    },
    min_size = "['max(monitor_w, monitor_h)*0.35', 'min(monitor_w, monitor_h)*0.35']",
})
hl.window_rule({
    match = {
        class = "^(dev\\.)?(noctalia\\.Noctalia(\\.Settings)?)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(dev\\.)?(noctalia\\.Noctalia(\\.Settings)?)$",
    },
    size = "['monitor_w*0.70', 'monitor_h*0.70']",
})
hl.window_rule({
    match = {
        class = "^(org\\.kde\\.dolphin)$",
        title = "negative:^(Moving.*|Create New.*|Extract.*|Compress.*|Copying.*|Progress.*|Configure.*|Properties.*|Choose\\sApplication.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(org\\.kde\\.dolphin)$",
        title = "negative:^(Moving.*|Create New.*|Extract.*|Compress.*|Copying.*|Progress.*|Configure.*|Properties.*|Choose\\sApplication.*)$",
    },
    move = "['max(20, min(cursor_x - (window_w*0.50), monitor_w - window_w + 20))', 'max(20, min(cursor_y - 50, monitor_h - window_h + 20))']",
})
hl.window_rule({
    match = {
        class = "^(org\\.kde\\.dolphin)$",
        title = "negative:^(Moving.*|Create New.*|Extract.*|Compress.*|Copying.*|Progress.*|Configure.*|Properties.*|Choose\\sApplication.*)$",
    },
    size = "['max(monitor_w, monitor_h)*0.50', 'min(monitor_w, monitor_h)*0.55']",
})
hl.window_rule({
    match = {
        class = "^(firefox|zen)$",
    },
    opacity = "1.0 override",
})
hl.window_rule({
    match = {
        class = "^(kitty|ghostty|[Kk]onsole|Alacritty|gnome-terminal|xfce[0-9]?-terminal)$",
    },
    opacity = "1.0 override",
})
hl.window_rule({
    match = {
        class = "^(mpv|org.kde.haruna|.*plex.*|org\\.kde\\.gwenview|.*vlc.*)$",
    },
    opacity = "1.0 override",
})
hl.window_rule({
    match = {
        class = "^(kvantummanager|qt[56]ct|nwg-look)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(org.pulseaudio.pavucontrol|blueman-manager|nm-applet|nm-connection-editor)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        title = "^(Winetricks.*|Protontricks.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        title = "^(Open|Authentication Required|Add Folder to Workspace|Choose Files|Save As|Confirm to replace files|File Operation Progress)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        initial_title = "^(Open File)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^([Xx]dg-desktop-portal-gtk)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        title = "^(File Upload|Choose wallpaper|Library)(.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(.*dialog.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        title = "^(.*dialog.*)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(hyprland-share-picker)$",
    },
    float = true,
})
hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})
hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        float = true,
        fullscreen = false,
        pin = false,
        title = "^$",
        xwayland = true,
    },
    no_focus = true,
})
hl.window_rule({
    name = "Steam Workspace",
    match = {
        class = "^(steam)$",
    },
    workspace = "special:Steam silent",
})
hl.window_rule({
    name = "Telegram Chat Workspace",
    match = {
        class = "^(org\\.telegram\\.desktop)$",
    },
    workspace = "special:Chat",
})
hl.window_rule({
    name = "Chrome Workspace",
    match = {
        class = "^(google\\-chrome)$",
    },
    workspace = "special:Chrome",
})
hl.window_rule({
    name = "Steam suppress activation",
    match = {
        class = "^(steam)$",
    },
    suppress_event = "maximize activate activatefocus",
})
hl.window_rule({
    name = "1Password",
    match = {
        class = "^(1password)$",
    },
    float = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("xhost +SI:localuser:root")
end)
